7/ reservation service and controller
LucianoSassano/Hotels-Project pull request #10
Opened 2020-06-11 03:46 UTC by martinhgonzalez

Happy path for CRUD for entities: Bedding, Room, Hotel and Reservation done.

Pending:

Incorporate City obj to the Hotel
incorporate User obj to the Reservation

2020-06-11 14:04 UTC, darioasaro approved these changes
To Long pull request, a lot of files for review.

2020-06-11 14:09 UTC, LucianoSassano requested changes

2020-06-11 14:09 UTC, LucianoSassano commented on src/main/java/com/example/demo/dto/room/RoomDtoOutput.java
> +
La anotacion Data de lombok incluye getters,setter, toString , Equals , hashcose y Allargsconstructor

2020-06-12 14:47 UTC, closed without merging

2020-06-12 15:10 UTC, martinhgonzalez commented
Closing because new Pull request (https://github.com/LucianoSassano/Hotels-Project/pull/14) covers those changes + task 8 (Exception Handling and Validation)