Exceptions added
LucianoSassano/Hotels-Project pull request #13
Opened 2020-06-12 14:09 UTC by LucianoSassano

2020-06-16 14:59 UTC, ghost requested changes

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/DemoApplication.java
> +import com.example.demo.model.Estate;
Si no los estamos usando deberiamos quitarlos

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/controller/CityController.java
> +        } catch (Exception e) {
Deberíamos ser mas específicos con las exceptions

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/controller/CityController.java
> +        } catch (Exception e) {
Deberíamos ser mas específicos con las exceptions

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/controller/CityController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Error " + e);
Si retornamos solo un string le complicamos la vida al front

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/dto/CityDto.java
> +    private Integer zipCode;
Esto va a salir en snakeCase

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/dto/CountryDto.java
> +    private List<Estate> states;
Estate o state?

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/dto/CountryDto.java
> +    }
Este te lo da el `@Data`

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/model/City.java
> +import javax.persistence.*;
Configurate esto desde el IDE

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/model/City.java
> +    @Column(name = "zipCode")
```suggestion
    @Column(name = "zip_code")
```

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/model/Country.java
> +import javax.persistence.*;
Configuralo

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/model/Estate.java
> +import javax.persistence.*;
*

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/model/Estate.java
> +public class Estate {
State o Estate?

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/repository/CityRepository.java
> +public interface CityRepository extends JpaRepository<CityDto, Integer> {
```suggestion
public interface CityRepository extends JpaRepository<City, Integer> {
```
El repo deberia ser de City

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/repository/CountryRepository.java
> +public interface CountryRepository extends JpaRepository<CountryDto, Integer> {
No deberian ser del DTO los repos

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/repository/StateRepository.java
> +public interface StateRepository extends JpaRepository<EstateDto, Integer> {
No deberian ser del dto los repos

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/service/CityService.java
> +    }
Usar el if (Optional.isPresent()){Optional.get()} es lo mismo que hacer if (algo != null). Intenta hacerlo con Optional.map

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/service/CityService.java
> +    }
Tirar la exception asi nomas, la Padre es poco entendible, hacete una custom

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/service/CityService.java
> +    }
:warning: 
```suggestion
    public CityDto getCity(Integer id) {

        return cityRepository.findById(id)
                .orElseThrow(UnaExceptionCustom::new);
    }
```

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/service/CountryService.java
> +        return this.countryRepository.findById(id).get();
```suggestion
        return this.countryRepository.findById(id).orElseThrow(CustomException::new);
```

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/service/CountryService.java
> +    }
Lo mismo que el otro comentario

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/service/StateService.java
> +    }
Intenta hacerlo con un .map

2020-06-16 14:59 UTC, MoyaFausto commented on src/main/java/com/example/demo/service/StateService.java
> +    }
```suggestion
    public EstateDto getById(Integer id) {
        return this.stateRepository.findById(id).orElseThrow(CustomException::new);
    }
```

2020-06-16 21:11 UTC, LucianoSassano commented on src/main/java/com/example/demo/dto/CountryDto.java
> +    private List<Estate> states;
State (que es la traduccion correcta de estado al ingles es una palabra reservada del sistema por lo cual me vi obligado a cometer este tipo voluntario)

2020-06-17 02:30 UTC, MoyaFausto commented on src/main/java/com/example/demo/dto/CountryDto.java
> +    private List<Estate> states;
Ok

2020-06-17 02:30 UTC, ghost approved these changes

2020-06-17 02:32 UTC, ghost requested changes

2020-06-17 02:32 UTC, MoyaFausto commented on src/main/java/com/example/demo/service/CityService.java
> +    }
.

2020-06-17 12:58 UTC, martinhgonzalez requested changes

2020-06-17 12:58 UTC, martinhgonzalez commented on src/main/java/com/example/demo/service/CityService.java
> +        }
Nos recomendaron no tirar excepcion en caso de que devuelva una List de algo vacia. Que simplemente la devuelva corchetes vacios y listo (Osea esta parte se sacaria para todos los casos similares que devuelvan lista)

2020-06-17 12:58 UTC, martinhgonzalez commented on src/main/resources/application.properties
> +spring.datasource.password=password
Esto habria que sacarlo y llevarlo a a una variable de entorno

2020-06-17 14:03 UTC, darioasaro commented on src/main/java/com/example/demo/controller/StateController.java
> +package com.example.demo.controller;
Chequear los espacios innecesarios

2020-06-17 14:04 UTC, darioasaro commented on src/main/java/com/example/demo/exception/notFoundException.java
> +}
agregar new line

2020-06-17 14:05 UTC, darioasaro commented on src/main/java/com/example/demo/util/ErrorMessage.java
> +    //public static final String INVALID_DATE_FORMAT = "Date format must be " + Constants.DATE_PATTERN;
Si no se usa, elimina la linea

2020-06-17 14:07 UTC, darioasaro commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/hotel_test
podes generar un app properties para tu propio entorno, incluyendolo en gitignore , y dejando un example en el app properties para que otros puedan generar el propio

2020-06-17 14:08 UTC, darioasaro approved these changes
Hay que trener cuidado con la cantidad de espacios innecesarios en el codigo

2020-06-19 13:34 UTC, martinhgonzalez approved these changes

2020-06-22 15:14 UTC, Frachuk approved these changes

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/DemoApplication.java
> +
Espacio de mas

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/controller/CityController.java
> +        return ResponseEntity.ok().body(this.cityService.listAllCities());
Se pueden dar exceptions aca tambien

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/controller/CityController.java
> +        this.cityService.delete(id);
Aca se puede dar que no encuentre el elemento a borrar

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/controller/CityController.java
> +        } catch (Exception e) {
Aca se esta levantando cualquier tipo de exception, pero se esta tratando como una notFound

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/controller/CountryController.java
> +        countryService.create(country);
Aca se puede ser mas descriptivo a la hora de crear el elemento, devolver el objeto creado o algo mas que un 200

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/controller/CountryController.java
> +            country.setId(id);
el set este lo pondria en el service

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/controller/CountryController.java
> +        this.countryService.deleteCountryById(id);
Puede ser que no se encuentre el elemento para ese id

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/controller/CountryController.java
> +    public ResponseEntity<HttpStatus> deleteCountry(@PathVariable Integer id){
Ojo con el diamond operator

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/model/City.java
> +    @Column(name = "id")
Acuerdense que las columnas si en la DB las tablas llevan el mismo nombre que los atributos se puede obviar la annotation @column

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/model/Estate.java
> +    @Column(name = "id")
@column

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/service/CityService.java
> +            throw new Exception();
Estaria bueno ponerle al menos un mensaje de que paso

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/service/CountryService.java
> +            throw new Exception();
Estaria bueno saber que paso aca en la exception

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/service/StateService.java
> +            throw new Exception();
Mensaje.

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/service/CityService.java
> +        Optional<CityDto> cityDb = this.cityRepository.findById(city.getId());
Por que aveces hacen referencia a this.cityRepository y otras veces simplemente cityRepository?

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/service/StateService.java
> +        Optional<EstateDto> stateDb = this.stateRepository.findById(state.getId());
this.stateRepository.findById(state.getId()); -> stateRepository.findById(state.getId());

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/service/StateService.java
> +        return this.stateRepository.findById(id).get();
this.stateRepository.findById(); -> puede ir sin el this

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/service/StateService.java
> +            EstateDto stateUpdate = stateDb.get();
Capaz que queda mas prolijo implementando builder

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/service/CountryService.java
> +            CountryDto countryUpdate = countryDb.get();
Se puede usar builder

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/service/CountryService.java
> +        Optional<CountryDto> countryDb = this.countryRepository.findById(country.getId());
this. demais

2020-06-22 15:14 UTC, Frachuk commented on src/main/java/com/example/demo/service/CityService.java
> +            CityDto cityUpdate = cityDb.get();
builder

2020-06-23 12:47 UTC, closed without merging