8/validation and exceptions
LucianoSassano/Hotels-Project pull request #14
Opened 2020-06-12 15:07 UTC by martinhgonzalez

Done: 
-CRUD for entities: Bedding, Room, Hotel and Reservation.
-Validation for all DTOs (input) fields.
-Global exception handling (Validation and Not Found) by ExceptionHandler class.

Pending:
Incorporate City obj to the Hotel entity
incorporate User obj to the Reservation entity

2020-06-12 15:46 UTC, Frachuk requested changes
En general lo veo bien, pero estandaricen el tema de el manejo de las exceptions ya que aca se realizo vía handlers y en el controller de luciano  via try catch

2020-06-12 15:46 UTC, Frachuk commented on src/main/java/com/example/demo/controller/BeddingController.java
> +        BeddingDto newBedding = beddingService.add(beddingDto);
Se puede devolver directamente sin necesidad de guardarlo en la newBedding

2020-06-12 15:46 UTC, Frachuk commented on src/main/java/com/example/demo/controller/BeddingController.java
> +        return ResponseEntity.ok(beddings);
return ResponseEntity.ok(beddingService.getAll());

2020-06-12 15:46 UTC, Frachuk commented on src/main/java/com/example/demo/controller/HotelController.java
> +package com.example.demo.controller;
En general tambien se pueden devolver los datos sin necesidad de instanciar una variable, ademas faltaria el caso de que cuando se quiera modificar algo en la DB no se encuentra como por ejemplo un id

2020-06-12 15:46 UTC, Frachuk commented on src/main/java/com/example/demo/dto/hotel/HotelDtoInput.java
> +//    @NotNull(message = "cityId cannot be null")
Esta por algo en particular comentado ?

2020-06-12 15:46 UTC, Frachuk commented on src/main/java/com/example/demo/dto/hotel/HotelDtoInput.java
> +}
new line

2020-06-12 15:46 UTC, Frachuk commented on src/main/java/com/example/demo/model/Bedding.java
> +}
newLine

2020-06-12 15:46 UTC, Frachuk commented on src/main/java/com/example/demo/service/BeddingService.java
> +}
newLine

2020-06-12 16:11 UTC, martinhgonzalez commented on src/main/java/com/example/demo/controller/HotelController.java
> +package com.example.demo.controller;
"ademas faltaria el caso de que cuando se quiera modificar algo en la DB no se encuentra como por ejemplo un id"
Te referis a la NotFoundException? Si no se encuentra, los metodos en el HotelService hacen el throw y el handler lo trata.

2020-06-12 16:12 UTC, martinhgonzalez commented on src/main/java/com/example/demo/dto/hotel/HotelDtoInput.java
> +//    @NotNull(message = "cityId cannot be null")
Cuando este mergeado lo de Lucho, lo descomento y deberia funcionar con algunos minimos cambios.

2020-06-12 16:15 UTC, martinhgonzalez commented on src/main/java/com/example/demo/dto/hotel/HotelDtoInput.java
> +}
No entenderia cual es la forma correcta de las new lines. En estos casos hay una con 2 lineas, una con 1, y otra con ninguna. Cual es la adecuada ?

2020-06-12 16:55 UTC, Frachuk commented on src/main/java/com/example/demo/dto/hotel/HotelDtoInput.java
> +}
Minimo te pide una new Line

2020-06-12 16:55 UTC, Frachuk commented on src/main/java/com/example/demo/controller/HotelController.java
> +package com.example.demo.controller;
Si lo vi después es que venia de ver como lo estaba manejando Lucho

2020-06-12 17:11 UTC, martinhgonzalez commented on src/main/java/com/example/demo/dto/hotel/HotelDtoInput.java
> +}
Ah, generar una linea por debajo de la linea 44 en este caso, digamos?

2020-06-16 20:04 UTC, ghost requested changes

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/dto/hotel/HotelDtoInput.java
> +//    private Long cityId;
Quitar comment

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/dto/hotel/HotelDtoOutput.java
> +//    private CityDto cityDto;
Quitar comment

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/dto/hotel/HotelDtoOutput.java
> +    private Integer roomCapacity;
Esto sale como camelCase

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/dto/hotel/HotelDtoOutput.java
> +//      this.cityDto = new cityDto(hotel.getCity());
quitar comment

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/dto/reservation/ReservationDtoOutput.java
> +    private Boolean isPaid;
Sale como camelCase

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/model/Bedding.java
> +import javax.persistence.*;
wildcard import

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/model/Hotel.java
> +//    private City city;
QUitar comment

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/model/Reservation.java
> +//    private User user;
quitar

2020-06-16 20:04 UTC, ghost commented on src/main/resources/application.properties
> +spring.datasource.password=1234556
Esto debería ser secreto, proba poniéndolo como variable de entorno y haciéndote un application-local.properties aprovechando los [profiles](https://www.baeldung.com/spring-profiles)

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/util/SharedUtils.java
> +    }
Esto no lo hace Jackson?

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/util/ErrorMessage.java
> +    public static final String NOT_POSITIVE = "Field must be a positive number";
Debe ser positivo o no ser positivo... Esa es la cuestión. Creo que deberia llamarse
```suggestion
    public static final String NOT_NEGATIVE = "Field must be a positive number";
```

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/util/Constants.java
> +    public static final String DATE_PATTERN = "dd-MM-yyyy";
Generalmente, las fechas se manejan como `yyyy-MM-dd`

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/service/RoomService.java
> +        updatedRoom.setBedding(bedding);        //Adding bedding and hotel to the entity (before this line it only had bedding and hotel id)
No hace falta el comentario

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/service/RoomService.java
> +    }
Yo retornaria `List<Room>` asi no acoplamos el service con la controller, quizas necesites este metodo en otro lado

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/service/RoomService.java
> +    }
Porque podria haber varios hoteles con el mismo id?

2020-06-16 20:04 UTC, ghost commented on src/main/java/com/example/demo/service/RoomService.java
> +        room.setHotel(hotel);               //The DTO only provides the id of the hotel, to do the insert. This line adds also the hotel data to our Room obj
No hace falta los comentarios

2020-06-16 23:31 UTC, martinhgonzalez commented on src/main/java/com/example/demo/dto/hotel/HotelDtoOutput.java
> +    private Integer roomCapacity;
Estaba manejando tanto para Response como para Request con camelCase. Recomendas entonces ambas operaciones todo con snake case ?

2020-06-17 00:25 UTC, martinhgonzalez commented on src/main/java/com/example/demo/service/RoomService.java
> +    }
En realidad es para obtener un listado de Rooms por ID de Hotel

2020-06-17 00:43 UTC, martinhgonzalez commented on src/main/java/com/example/demo/service/RoomService.java
> +    }
No comprendo porque se reduciría el acoplamiento mandando una List<Room>. En ese caso, el Controller luego debería tomar esas Rooms y procesarlas para poder crear DTOS de salida.

Es responsabilidad del Controller instanciar los DTOS ?

2020-06-17 01:42 UTC, martinhgonzalez commented on src/main/java/com/example/demo/util/SharedUtils.java
> +    }
Con el @Pattern y el regex que filtra para el @Valid, permite fechas yyyy MM dd, tanto con "/" como "." y "-" como separadores. Esa funcion lo que hace es reemplazarlo al formato que acepta LocalDate default que es con "-" como separadores. Tengo que investigar mas a ver si puedo reemplazarlo con alguna/s annotations de Jackson

2020-06-17 14:11 UTC, darioasaro approved these changes
Tendrias que chequear los espacios y saltos de linea innecesarios.

2020-06-17 15:08 UTC, Frachuk commented on src/main/java/com/example/demo/dto/hotel/HotelDtoInput.java
> +  private Integer rating;
El rating hace referencia a las estrellas?

2020-06-17 15:15 UTC, Frachuk commented
Por lo que vi mejoro un montón la legibilidad del código con el formatter, seria lo ideal que se lo pasen a todos los files y estaría por mi parte

2020-06-17 15:31 UTC, martinhgonzalez commented on src/main/java/com/example/demo/dto/hotel/HotelDtoInput.java
> +  private Integer rating;
Correcto. Podriamos limitarlo de a 1-5 con un enum o simplemente validando con @Size esos min y max

2020-06-18 04:12 UTC, Frachuk commented on src/main/java/com/example/demo/dto/hotel/HotelDtoInput.java
> +  private Integer rating;
Me hacía más ruido que sea algo sin coma el cual capaz estaría bueno tener una Review como de tipo double

2020-06-19 14:26 UTC, LucianoSassano approved these changes

2020-06-22 11:59 UTC, Frachuk approved these changes

2020-06-23 12:48 UTC, merged