Exception handler and builder
LucianoSassano/Hotels-Project pull request #16
Opened 2020-06-23 12:50 UTC by LucianoSassano

-Swagger documentation added
-Global exception handler implemented
-Builder implemented

2020-06-23 13:57 UTC, martinhgonzalez approved these changes

2020-06-23 15:21 UTC, Frachuk requested changes

2020-06-23 15:21 UTC, Frachuk commented on src/main/java/com/example/demo/util/ErrorMessage.java
> +    //public static final String INVALID_DATE_FORMAT = "Date format must be " + Constants.DATE_PATTERN;
Quedo comentado por algo en particular ?

2020-06-23 15:21 UTC, Frachuk commented on src/main/java/com/example/demo/service/StateService.java
> +        stateRepository.findById(id).orElseThrow(() -> new notFoundException(ErrorMessage.STATE_NOT_FOUND));
Esta es la manera de preguntar si esta ?

2020-06-23 15:21 UTC, Frachuk commented on src/main/java/com/example/demo/service/StateService.java
> +        if (estateDtoList.isEmpty()) {
chicos ya les dije que no esta mal devolver una lista vacia, en mas se busca eso no una exception

2020-06-23 15:21 UTC, Frachuk commented on src/main/java/com/example/demo/service/CountryService.java
> +        List<CountryDto> cityDtoList = countryRepository.findAll()
Esto tiene mal el nombre de las variables deberia ser countryDtoList y lo mismo no estaria mal devolver la lista vacia si no hay

2020-06-23 15:21 UTC, Frachuk commented on src/main/java/com/example/demo/dto/EstateDto.java
> +    @NotEmpty(message = "cities cannot be empty")
Esto puede ir en una constante como los mensajes anteriores

2020-06-23 15:21 UTC, Frachuk commented on src/main/java/com/example/demo/model/City.java
> +    @Column(name = "zip_code")
Annotation de mas

2020-06-23 15:21 UTC, Frachuk commented on src/main/java/com/example/demo/repository/CityRepository.java
> +public interface CityRepository extends JpaRepository<City, Integer> {
Chicos fijense que algunos estan usando Long como tipo de dato para los ID ponganse de acuerdo

2020-06-23 15:21 UTC, Frachuk commented on src/main/java/com/example/demo/repository/CityRepository.java
> +    Optional<City> findCityByZip(@Param("zip_code") Integer zip_code);
El orm no te da esta query sin necesidad de hacerla custom ?

2020-06-24 13:33 UTC, darioasaro approved these changes

2020-06-25 01:29 UTC, martinhgonzalez commented on src/main/java/com/example/demo/repository/CityRepository.java
> +    Optional<City> findCityByZip(@Param("zip_code") Integer zip_code);
Esto es todo un tema del soft delete. Las usamos asi porque queremos obtener el resultado incluso si su campo "is_deleted" en la BD figura como true.

Todas las queries predeterminadas del orm no traen los que tengan "is_deleted" true, por la etiqueta @Where que pusimos en las entidades (Mirar para este caso la clase City).

2020-06-25 01:31 UTC, martinhgonzalez commented on src/main/java/com/example/demo/service/StateService.java
> +        stateRepository.findById(id).orElseThrow(() -> new notFoundException(ErrorMessage.STATE_NOT_FOUND));
Correcto. No se guarda en ninguna variable porque no reutilizamos lo que retorna, simplemente queremos ver si existe o no. Y en caso que no, lanzar esa excepción.

2020-06-25 15:45 UTC, Frachuk approved these changes

2020-06-26 14:26 UTC, merged