Ticket n°17 refactor area dtos and services
LucianoSassano/Hotels-Project pull request #33
Opened 2020-07-02 16:05 UTC by LucianoSassano

-Unique dto changed for input and output dto
-Service and controller adapted to work with new dtos
-Entity restoration funcionality added

2020-07-07 21:51 UTC, darioasaro commented on src/main/java/com/example/demo/model/City.java
>    void preInsert() {
si el metodo no  hace nada, tal vez deberias sacarlo

2020-07-07 21:51 UTC, darioasaro commented on src/main/java/com/example/demo/model/City.java
>          .zip_code(cityDto.getZipCode())
guarda con las lineas que quedan en blanco

2020-07-07 21:53 UTC, darioasaro commented on src/main/java/com/example/demo/model/Estate.java
> +  @NotNull @PositiveOrZero private Long countryId;
en algunas clases tenes las anotaciones arriba de la declaracion de la variable,y en otras como aca a la izquierda.

2020-07-07 22:02 UTC, darioasaro requested changes
chequea en el repositorio de country y de estado que hay queries que se inyectan mediante JPA

2020-07-07 22:02 UTC, darioasaro commented on src/main/java/com/example/demo/repository/CountryRepository.java
> +  Optional<Country> findCountryById(@Param("id") Long id);
no hace falta especificar la query, en este tipo de casos el repositorio de jpa indicandole las palabras reservadas que estas usando en la firma del metodo ya inyecta

2020-07-07 22:02 UTC, darioasaro commented on src/main/java/com/example/demo/repository/StateRepository.java
> +  Optional<Estate> findStateById(@Param("id") Long id);
no hace falta especificar la query, en este tipo de casos el repositorio de jpa indicandole las palabras reservadas que estas usando en la firma del metodo ya inyecta

2020-07-07 22:13 UTC, LucianoSassano commented on src/main/java/com/example/demo/model/Estate.java
> +  @NotNull @PositiveOrZero private Long countryId;
es por el formater!!

2020-07-13 12:14 UTC, darioasaro approved these changes

2020-07-13 12:41 UTC, martinhgonzalez approved these changes

2020-07-13 12:52 UTC, merged