Task2
LucianoSassano/Hotels-Project pull request #4
Opened 2020-06-05 13:21 UTC by darioasaro

User entities create done.

2020-06-05 19:24 UTC, Frachuk reviewed
Este PR apunta a master por ?? y la descripcion task2 de la branch no es la recomendada intentaria poner algo mas descriptivo acuerdense de tratar de implementar gitflow, feature/task-2-user-entities

2020-06-05 19:24 UTC, Frachuk commented on src/main/java/com/example/demo/model/CreditCard.java
> +    private Integer id;
Yo utilizaría Long ( es una recomendación )

2020-06-05 19:24 UTC, Frachuk commented on src/main/java/com/example/demo/model/User.java
> +    @JsonFormat(shape= JsonFormat.Shape.STRING, pattern="dd-MM-yyyy")
dd-MM-yyyy Lo pondria en una class util o un enum o directamente setearlo en la config del properties para que los trate de determinada manera 

![image](https://user-images.githubusercontent.com/23116358/83914766-47a98f80-a748-11ea-98bf-67b11b694d6e.png)

2020-06-05 19:24 UTC, Frachuk commented on src/main/java/com/example/demo/model/User.java
> +    @JsonFormat(shape= JsonFormat.Shape.STRING, pattern="dd-MM-yyyy")
igual con respecto a esto no estas guardando los milisegundos un registro se puede crear o modificar varias veces en un dia
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd@HH:mm:ss.SSSZ")

2020-06-05 19:24 UTC, Frachuk commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
Dejenle siempre una newline a el fnal del file

2020-06-05 19:24 UTC, Frachuk commented on src/main/java/com/example/demo/controller/UserController.java
> +package com.example.demo.controller;
Este file si no tiene funcionalidad yo no lo tiraría en el pr, que es como un health check al momento ? no hace nada

2020-06-10 13:37 UTC, Frachuk requested changes
Tiene comentarios pendientes y sigue apuntando a master

2020-06-11 12:27 UTC, darioasaro commented on src/main/java/com/example/demo/controller/UserController.java
> +package com.example.demo.controller;
con las correcciones hechas y en el nuevo commit ya posee funcionalidad

2020-06-11 12:27 UTC, darioasaro commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
fixed!

2020-06-11 12:28 UTC, darioasaro commented on src/main/java/com/example/demo/model/User.java
> +    @JsonFormat(shape= JsonFormat.Shape.STRING, pattern="dd-MM-yyyy")
se cambio el tipo de dato por localdatetime que ya formatea con ese patron

2020-06-11 12:28 UTC, darioasaro commented on src/main/java/com/example/demo/model/CreditCard.java
> +    private Integer id;
fixed!

2020-06-11 12:46 UTC, closed without merging