initial commit
LucianoSassano/Hotels-Project pull request #5
Opened 2020-06-07 00:03 UTC by LucianoSassano

2020-06-08 15:06 UTC, Frachuk commented
Que es esto y por que va a master?

2020-06-10 13:35 UTC, Frachuk requested changes

2020-06-10 13:35 UTC, Frachuk commented on src/main/java/com/example/demo/repository/CityRepository.java
> +public interface CityRepository extends JpaRepository<City,Integer> {
No es necesario sobrescribir todo lo de JpaRepository en mas no creo que sea lo que realmente quieras, por ejemplo el findAll te va a devolver null y asi con los demas metodos generalmente va vacio salvo alguna query custom esta interface

2020-06-10 13:35 UTC, Frachuk commented on src/main/java/com/example/demo/repository/CityRepository.java
> +public interface CityRepository extends JpaRepository<City,Integer> {
Lo mismo para los otros repositories

2020-06-10 23:16 UTC, LucianoSassano commented on src/main/java/com/example/demo/repository/CityRepository.java
> +public interface CityRepository extends JpaRepository<City,Integer> {
Fran gracias por las correcciones , sii ! lo implemente porque me lo marcaba la ide , mas adelante me choque con eso y lo volví a dejar vació , en el ultimo pr se encuentra como me señalas

2020-06-10 23:18 UTC, LucianoSassano reviewed
Repositoy class of each Area entity changed

2020-06-12 13:49 UTC, Frachuk approved these changes

2020-06-12 13:54 UTC, merged