feature2/Area controllers
LucianoSassano/Hotels-Project pull request #7
Opened 2020-06-09 02:13 UTC by LucianoSassano

2020-06-10 13:39 UTC, Frachuk commented on src/main/java/com/example/demo/controller/CountryController.java
> +    @DeleteMapping("countries/{id}")
Creo que hay un tipo en la ruta le faltaria al principio el slash /

2020-06-10 13:46 UTC, Frachuk requested changes

2020-06-10 13:46 UTC, Frachuk commented on src/main/java/com/example/demo/controller/CountryController.java
> +        country.setId(id);
Lo haria dentro del mismo updateCountry

2020-06-10 13:46 UTC, Frachuk commented on src/main/java/com/example/demo/repository/StateRepository.java
> +public interface StateRepository extends JpaRepository<Estate,Integer> {
No se por que querrias sobreescribir todos lo de JpaRepository

2020-06-10 13:46 UTC, Frachuk commented on src/main/java/com/example/demo/model/City.java
> +    @Column(name = "id")
Hace falta poner el @column(name) cuando es identico a el nombre del atributo ?

2020-06-10 23:37 UTC, LucianoSassano reviewed
Changes made according to tutors specification

2020-06-12 13:55 UTC, Frachuk commented
Tiene conflictos despues de un merge previo

2020-06-12 13:57 UTC, closed without merging